version: '3'
services:
  php:
    build: build/php
    expose:
      - '9000'
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/coupon:cached
      - ./logs:/var/log
  web:
    build: build/nginx
    restart: always
    ports:
        - ‘81:80'
    depends_on:
        - php
    volumes:
        - ./:/var/www/html/coupon:cached
        - ./logs:/var/log/nginx

